### ISSUE TITLE
Is the weight file wrong?

### ISSUE THREAD

**Issue by NiFangBaAGe** [ZhiHanZ/IRIS0-SPAN#4]
Hi,

I am very interested in SPAN. However, I find something wrong when I try to run it.

Traceback (most recent call last):
  File "evaluator.py", line 39, in <module>
    model.load_weights(weight_file)
  File "/home/ipprlab/anaconda3/envs/py3/lib/python3.6/site-packages/keras/engine/network.py", line 1166, in load_weights
    f, self.layers, reshape=reshape)
  File "/home/ipprlab/anaconda3/envs/py3/lib/python3.6/site-packages/keras/engine/saving.py", line 1030, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 1 layers into a model with 12 layers.

Is the weight file wrong?

Thanks.

**Comment by siweic0818** [comment]
Did you use model = keras.utils.multi_gpu_model( model, 2)? The saved weights are created by multiple gpus so if you are using single gpu then the weights won't load.

**Comment by brightendavid** [comment]
is there any weight saved in single gpu?to get multi gpu is to hard for me.

**Comment by michiganleon** [comment]
Dear David,

You can try to load the model in multi-gpu model and then transform the model into single GPU. For tensorflow you can check this code: https://stackoverflow.com/questions/41342098/keras-load-checkpoint-weights-hdf5-generated-by-multiple-gpus <https://stackoverflow.com/questions/41342098/keras-load-checkpoint-weights-hdf5-generated-by-multiple-gpus>
This is keras but I remember normal TF model can be loaded similarly. (Using model.layers[-2])

Sincerely,
Xuefeng

**Comment by 85zhanghao** [comment]
I have the same problem, have you solved it ?“ValueError: You are trying to load a weight file containing 1 layers into a model with 12 layers.”
